import localFont from "next/font/local";
import "./globals.css";
import dynamic from "next/dynamic";
const Sidebar = dynamic(() => import("./components/Sidebar"));
const Navbar = dynamic(() => import("./components/Navbar"));
const Footer = dynamic(() => import("./components/Footer"));

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="flex">
          <aside>
            <Sidebar></Sidebar>
          </aside>
          <section className="flex-1">
            <header  className="sticky top-0 z-50">
              <Navbar></Navbar>
            </header>
            <main className="bg-[#ECF0F4]">
              {children}
            </main>
            <footer>
              <Footer></Footer>
            </footer>
          </section>
        </section>
      </body>
    </html>
  );
}
