import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="flex">
          <aside>
            <Sidebar></Sidebar>
          </aside>
          <section className="flex-1">
            <header>
              <Navbar></Navbar>
            </header>
            <main className="min-h-[calc(120vh-232px)]">
              {children}
            </main>
            <footer>
              <Footer></Footer>
            </footer>
          </section>
        </section>
      </body>
    </html>
  );
}
